name: Deploy Docs Preview

on:
  workflow_dispatch:  # Allows triggering the workflow manually in GitHub UI

# If another push to the same PR or branch happens while this workflow is still running,
# cancel the earlier run in favor of the next run.
#
# There's no point in testing an outdated version of the code. GitHub only allows
# a limited number of job runners to be active at the same time, so it's better to cancel
# pointless jobs early so that more useful jobs can run sooner.
concurrency:
  group: exports-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-docs-preview:
    name: Deploy Preview Docs to Vercel
    runs-on: ubuntu-latest
    environment: Staging
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.PR_COMMENT_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
      - name: Build Project Artifacts
        run: vercel build --token="$VERCEL_TOKEN"
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token="$VERCEL_TOKEN" > deployment-url.txt
      - name: Post Preview URL Comment
        run: gh pr comment "$PR_URL" -F deployment-url.txt
